create table promo_codes (
    id bigint primary key generated by default as identity,
    discount double precision not null check (discount > 0.0) check (discount <= 1.0),
    value varchar(50) not null
)