create table rides (
    id bigint primary key generated by default as identity,
    cost numeric(8, 4) not null check (cost > 0.0),
    driver_id bigint,
    passenger_id bigint not null check (passenger_id > 0),
    started_at timestamp(6),
    ended_at timestamp(6),
    source_address_id bigint not null references addresses(id) on delete cascade,
    status varchar(20) not null
)