package by.modsen.taxiprovider.paymentservice.util;

import lombok.experimental.UtilityClass;

@UtilityClass
public class Message {
    public final String MONTH_MINIMAL_VALUE_IS_INVALID = "Minimal value of month's number is '1'.";
    public final String MONTH_MAXIMUM_VALUE_IS_INVALID = "Maximum value of month's number is '12'.";
    public final String CVC_MINIMAL_VALUE_IS_INVALID = "Minimal value of month's number is '1'.";
    public final String CVC_MAXIMUM_VALUE_IS_INVALID = "Minimal value of month's number is '1'.";
    public final String CARD_NUMBER_IS_EMPTY = "Card's number must be not empty.";
    public final String EXPIRATION_MONTH_IS_NULL = "Expiration month can't be null.";
    public final String EXPIRATION_YEAR_IS_NULL = "Expiration year can't be null.";
    public final String CVC_IS_NULL = "CVC code can't be null.";
    public final String AMOUNT_IS_NULL = "Amount must be not null.";
    public final String AMOUNT_MINIMAL_VALUE_IS_INVALID = "Minimal value of amount is '0.01'.";
    public final String CARD_NUMBER_BODY_IS_INVALID = "Wrong format of card's number.";
    public final String CURRENCY_IS_EMPTY = "Currency must be not empty.";
    public final String CARD_TOKEN_IS_EMPTY = "Card's token must be not empty.";
    public final String TAXI_USER_ROLE_IS_EMPTY = "Taxi user's role must be not empty.";
    public final String TAXI_USER_ID_IS_NULL = "Taxi user's id must be not null.";
    public final String TAXI_USER_ID_IS_INVALID = "Minimal value of taxi user's id is '1'.";
    public final String TAXI_USER_ALREADY_EXISTS = "Taxi user with id '%d' and role '%s' already exists.";
    public final String CUSTOMER_NAME_IS_EMPTY = "Customer's name must be not empty.";
    public final String CUSTOMER_NAME_IS_INVALID = "Customer's name can contain only letters and spaces.";
    public final String CUSTOMER_EMAIL_IS_EMPTY = "Customer's email must be not empty.";
    public final String CUSTOMER_EMAIL_IS_INVALID = "Wrong email format.";
    public final String CUSTOMER_PHONE_NUMBER_IS_EMPTY = "Customer's phone number must be not empty.";
    public final String CUSTOMER_PHONE_NUMBER_IS_INVALID = "Wrong format of phone number.";
    public final String BALANCE_IS_NULL = "Balance must be not null.";
    public final String BALANCE_VALUE_IS_INVALID = "Minimal value of balance is '0.01'.";
    public final String USER_NOT_FOUND = "User with id '%d' and role '%s' wasn't found.";
    public final String CUSTOMER_NOT_FOUND = "Customer with email '%s' wasn't created.";
    public final String NOT_ENOUGH_MONEY_ON_BALANCE = "Not enough money on the balance.";
    public final String EXTERNAL_SERVICE_IS_UNAVAILABLE = "Cannot connect to rating's service.";
    public final String EXTERNAL_SERVICE_ERROR = "Cannot get response from the driver's service.";
    public final String PASSENGER_ID_IS_INVALID = "Passenger's id must be a number and can't be less than one.";
    public final String DRIVER_ID_IS_INVALID = "Driver's id must be a number and can't be less than one.";
    public final String CANNOT_GET_RESPONSE_FROM_EXTERNAL_SERVICE = "External service '%s' failed to process after max retries.";
    public final String BANK_CARD_EXPIRATION_IS_INVALID = "Bank card's expiration is invalid.";
    public final String CREATING_USER_ALREADY_EXISTS = "Creating user already exists (existing params: '%d', '%s').";
    public final String PAYING_BY_CARD = "Paying by not saved card.";
    public final String PAYMENT_IS_SUCCESSFUL = "The payment is successful.";
    public final String CREATING_A_CARD_TOKEN = "Creating a new card token.";
    public final String CARD_TOKEN_CREATION_IS_SUCCESSFUL = "A new card token is created successfully.";
    public final String CREATING_NEW_CUSTOMER = "A new customer is creating.";
    public final String NEW_CUSTOMER_WAS_CREATED = "The customer '%s' was created.";
    public final String UPDATING_CUSTOMER = "The customer '%d' is updating.";
    public final String CUSTOMER_WAS_UPDATED = "The customer '%d' was updated.";
    public final String DELETING_CUSTOMER = "The customer '%d', '%s' is deleting.";
    public final String CUSTOMER_WAS_DELETED = "The customer '%d', '%s' was deleted.";
    public final String CHARGING_BY_CUSTOMER = "Charging by a saved card from customer '%d', '%s'.";
    public final String CHARGE_BY_CUSTOMER_IS_SUCCESSFUL = "Charging from customer '%d', '%s' is successful.";
    public final String UPDATING_CUSTOMER_BALANCE = "Updating the balance of the customer '%s'.";
    public final String UPDATING_CUSTOMER_BALANCE_IS_SUCCESSFUL = "The balance of the customer '%s' updated successfully.";
    public final String UPDATING_DRIVER_BALANCE = "Transferring the money of the driver '%d'.";
    public final String UPDATING_DRIVER_BALANCE_IS_SUCCESSFUL = "The money of the driver '%d' transferred successfully.";
    public final String CHECKING_CUSTOMER_BALANCE = "Checking the balance of the customer '%s'.";
    public final String CUSTOMER_HAS_ENOUGH_MONEY = "Customer '%s' has enough money.";
    public final String CUSTOMER_HAS_NOT_ENOUGH_MONEY = "Customer '%s' hasn't enough money.";
    public final String CREATING_NEW_PAYMENT_METHOD = "Creating a new payment method for customer '%s'.";
    public final String NEW_PAYMENT_METHOD_WAS_NOT_CREATED = "A new payment method wasn't created.";
    public final String NEW_PAYMENT_METHOD_WAS_CREATED = "A new payment method was created.";
    public final String GETTING_CUSTOMER_BALANCE = "Getting the balance of the customer '%s'";
    public final String SAVING_NEW_USER = "Saving new user.";
    public final String NEW_USER_WAS_SAVED = "The user '%d', '%s' was saved.";
    public final String DELETING_USER = "The user '%d', '%s' is deleting.";
    public final String USER_WAS_DELETED = "The user '%d', '%s' was deleted.";
}
