create table drivers (
    id bigint primary key generated by default as identity,
    lastname varchar(50) not null,
    firstname varchar(50) not null,
    email varchar(50) not null unique,
    password varchar(250) not null,
    role varchar(20) not null,
    phone_number varchar(20) not null unique,
    status varchar(20) not null,
    balance numeric(38,2) not null,
    ride_status varchar(20) not null
)