create table ratings (
    id bigint primary key generated by default as identity,
    value int not null,
    created_at timestamp not null,
    driver_id bigint not null references drivers(id) on delete cascade
);