create table ratings (
    id bigint primary key generated by default as identity,
    value int not null,
    created_at date not null,
    driver_id bigint not null
);

alter table ratings add foreign key (driver_id) references drivers (id) on delete cascade;

