create table ratings (
    id bigint primary key generated by default as identity,
    value int not null check (value > 0) check (value <= 5),
    created_at timestamp not null,
    passenger_id bigint not null references passengers(id) on delete cascade
)